# Given:
#   - an AWS SSM Parameter AWS_TEST_SECRET='foobar' (SecureString, using default encryption key)
# Provides:
#   - An environment variable THE_SECRET='foobar' to the nginx container
#
# Test this file by launching aws-ssm, then run:
#     kubectl apply -f example.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  annotations:
    alpha.ssm.cmattoon.com/aws-param-name: PROD_DB_PASSWORD
    alpha.ssm.cmattoon.com/aws-param-type: SecureString
    alpha.ssm.cmattoon.com/aws-param-key: "alias/aws/ssm"
data: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-pod
  labels:
    app: my-test
spec:
  template:
    metadata:
      labels:
        app: my-test
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: http
              containerPort: 80
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: test-secret
                  key: SecureString
