 {{ if and (ne .Values.aws.secret_key "") (ne .Values.aws.access_key "") -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-ssm-credentials
type: Opaque
data:
  AWS_ACCESS_KEY: "{{ .Values.aws.access_key | b64enc }}"
  AWS_SECRET_KEY: "{{ .Values.aws.secret_key | b64enc }}"
{{ end -}}
