---
apiVersion: v1
kind: Secret
metadata:
  name: aws-ssm-credentials
type: Opaque
stringData:
        AWS_REGION:  "{{ .Values.aws.region }}"
        AWS_ACCESS_KEY: "{{ .Values.aws.access_key }}"
        AWS_SECRET_KEY: "{{ .Values.aws.secret_key }}"
